language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository

script:
- if [ "$TRAVIS_BRANCH" = "master" ]; then ./gradlew firAll; else ./gradlew aR; fi