language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository

script:
- if [ "$TRAVIS_BRANCH" = "master" ]; then ./gradlew -Ptoken=f4786cd4c091c1f8e6f1f9688694aa38 firAll; else ./gradlew aR; fi